language: php
matrix:
  include:
  - php: 7.2
    env: PREFER_LOWEST=""
  - php: 7.1
    env: PREFER_LOWEST=""
#  - php: 7.1
#    env: PREFER_LOWEST="--prefer-lowest"

before_script:
- composer update $PREFER_LOWEST --no-interaction
- mkdir -p build/logs
script:
- "./vendor/bin/phpunit"
#- "./vendor/bin/composer-require-checker --config-file=composer-require-checker.json"
- composer cs-check
- composer phpstan
after_script:
- travis_retry php vendor/bin/php-coveralls
