language: php
matrix:
  include:
  - php: 7.3
    env: PREFER_LOWEST=""
  - php: 7.2
    env: PREFER_LOWEST=""
  - php: 7.1
    env: PREFER_LOWEST=""

cache:
  directories:
  - generator/doc/doc-en
  - vendor
  - generator/vendor
  - $HOME/.composer

before_script:
- cd generator && composer install --no-interaction && cd ..
- |
  if [ ! -d "generator/doc/doc-en/en" ]; then
    cd generator/doc
    svn co https://svn.php.net/repository/phpdoc/modules/doc-en doc-en
    cd ../..
  else
    cd generator/doc/doc-en
    svn update
    if [ $? -ne 0 ];
    then
      cd ..
      rm -rf doc-en
      svn co https://svn.php.net/repository/phpdoc/modules/doc-en doc-en
      cd doc-en
    fi
    cd ../../..
  fi
- composer update

script:
- cd generator && ./vendor/bin/phpunit && cd ..
- cd generator && composer cs-check && cd ..
- cd generator && composer phpstan && cd ..
- composer dump-autoload
- composer cs-check
- composer phpstan
# Now, let's regenerate all files and see if we obtain the same set of files as the ones commited:
- cd generator && ./safe.php generate && cd ..
- |
  if output=$(git status --porcelain) && [ -z "$output" ]; then
    # all is good
    echo "Generated files are the same as committed file: OK"
  else
    # Uncommitted changes
    echo "Generated files are different from commited files. Please run './safe.php generate' command and commit the results."
    exit 1;
  fi

after_script:
- cd generator && travis_retry php vendor/bin/php-coveralls -v
